### ISSUE TITLE
reddit module

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#105]
use [django-th-ansible](https://github.com/foxmask/django-th-ansible) to bootstrap the module from the skelton `django-th-ansible`, then use [reddit api](https://github.com/praw-dev/praw/)

then, info to collect:

- is oauth used (v1 or v2 ) ?? 
- is there any date that permits to grab only the data we need ?

if yes : 

in the model Reddit, a subreddit field should be enough for a beginning.

**Comment by foxmask** [comment]
made a Wiki page as "a Box of Ideas" https://github.com/foxmask/django-th/wiki/Modules-To-Do

**Comment by h-chauhan** [comment]
Okay, I'll pick up this one. Please label it as hacktoberfest.

I'll try to check it out by tomorrow. 👍

**Comment by foxmask** [comment]
Brave!

**Comment by foxmask** [comment]
Hi,

We should get the title when just the url is posted or the title and the content of the post when it's not just an url that is shared

**Comment by foxmask** [comment]
Ho my god, my posted has been truncated

**Comment by foxmask** [comment]
Hi,
We need to test that the Oauth workflow is triggered to get the precious token that will be used all along the exchange the the API.
once the token is grab the reddit.com, we store it in UserService for the current user and for the ServiceReddit.

As with reddit we can create posts or share links.

So I think that the data we can get from Reddit is Link or Post (we have to have a look at the api to see what is provided for that)

the read_data will allow us to get the data. I hope that with the API we could spot if it"s just a normal post (with a title and a content) or a post to share just a link. (with no content)

the save_data will allow us to create a post to share link or not. To know if we post a share link or a complet post with title and content, it's the role of the ServiceReddit omdel where I imagine we just need to add a boolean field "share_link".
Then  in the ConsumerForm we will just need to add this field. When the user tick the boolean field, then the data that save_data will handle will be just to create post with link. Otherwise , a normal post.

If i'm not clear just tell me I will show you example.
Regards





the save_data

**Comment by foxmask** [comment]
i'm going to make a summary of how the project work :) that could be fine to see how things communicate with each others.

**Comment by foxmask** [comment]
did that https://blog.trigger-happy.eu/pages/TriggerHappy.pdf 
hope this could be helpful

**Comment by h-chauhan** [comment]
I've updated my PR. Review please.

**Comment by foxmask** [comment]
For the moment I dont close the issue because the API is blocking during posting ...

**Comment by foxmask** [comment]
Found the correct scope to be able to create post.
