### ISSUE TITLE
Better installation note.

### ISSUE THREAD

**Issue by unnikked** [foxmask/django-th#116]
Sorry to ask a silly question but since I'm not familiar with the python django stack I find difficult to have a working instance of this project. 

After followed the installation documentation I don't know how to start all the process, could you please provide further information for this step ?

**Comment by foxmask** [comment]
Hi,
it's no false ;)

once you have setup supervisord, when you start it, everything is ready to use. There is nothing else to do.

    /etc/init.d/supervisord start

a detail, from this config file you need to add to supervisor : 

	[program:django_th_worker]
	user = foxmask
	directory=/home/projects/trigger-happy/th
	command=/home/projects/trigger-happy/bin/celery -A django_th worker --autoscale=10,3 -l info
	autostart=true
	autorestart=true
	redirect_stderr=true
	stdout_logfile=/home/projects/trigger-happy/logs/trigger-happy.log
	stderr_logfile=/home/projects/trigger-happy/logs/trigger-happy-err.log

	[program:django_th_beat]
	user = foxmask
	directory=/home/projects/trigger-happy/th
	command=/home/projects/trigger-happy/bin/celery -A django_th beat -l info
	autostart=true
	autorestart=true
	redirect_stderr=true
	stdout_logfile=/home/projects/trigger-happy/logs/trigger-happy.log
	stderr_logfile=/home/projects/trigger-happy/logs/trigger-happy-err.log

the parameter directory must point to the path of your virtualenv. Here the path is just for the example.

once supervisord is started, enter : 

supervisorctl status to see this kind of thing 

    supervisorctl status
    django_th_beat                   RUNNING    pid 30597, uptime 4 days, 14:27:51
    django_th_web                    RUNNING    pid 30577, uptime 4 days, 14:28:01
    django_th_worker                 RUNNING    pid 30614, uptime 4 days, 14:27:50

when supervisor fails to start, the status is not RUNNED but FAILED

If you are still not able to start the instance, tell me where you are stuck / what you need.

**Comment by foxmask** [comment]
I forgot to add the "web" part ; the previsous config for supervisor was just for the celery stuff

here is how to start the web worker

	[program:django_th_web]
	environment = LANG="fr_FR.UTF-8", LC_ALL="fr_FR.UTF-8", LC_LANG="fr_FR.UTF-8"
	user = foxmask                                                        ; User to run as
	directory = /home/projects/trigger-happy/th
	command = /home/projects/trigger-happy/bin/gunicorn_start             ; Command to start app
	autostart = true
	autorestart = true
	redirect_stderr=true
	stdout_logfile = /home/projects/trigger-happy/logs/gunicorn-start.log ; Where to write log messages
	stderr_logfile = /home/projects/trigger-happy/logs/gunicorn-start-err.log ; Where to write log messages

**Comment by unnikked** [comment]
I just installed it using the pip command, but I cannot find the home folder of the project, where do I find it ?

**Comment by foxmask** [comment]
it's the one you made with the command pyvenv-3.4 or pyvenv

this one create what we call a virtualenv, from which we can install a dedicated environment for a project A. Then if we need to install a project B with different lib of python, we do another pyvenv 

for example : 

    foxmask@foxmask:~ $  pyvenv-3.4 unniked
    foxmask@foxmask:~ $  cd $_
    foxmask@foxmask:~/unniked $  ls
    bin  include  lib  lib64  pyvenv.cfg
    foxmask@foxmask:~/unniked $  source bin/activate
    (unniked) foxmask@foxmask:~/unniked $  python --version
    Python 3.4.2

then from here i do pip install django-th 
then you create a django project 

    (unniked) foxmask@foxmask:~/unniked $  django-admin startproject myproject
    (unniked) foxmask@foxmask:~/unniked $  ls -l
    total 20
    drwxr-xr-x 3 foxmask foxmask 4096 oct.  29 16:30 bin
    drwxr-xr-x 2 foxmask foxmask 4096 oct.  29 16:28 include
    drwxr-xr-x 4 foxmask foxmask 4096 oct.  29 16:28 lib
    lrwxrwxrwx 1 foxmask foxmask   25 oct.  29 16:28 lib64 -> /home/foxmask/unniked/lib
    drwxr-xr-x 3 foxmask foxmask 4096 oct.  29 16:31 myproject
    -rw-r--r-- 1 foxmask foxmask   69 oct.  29 16:28 pyvenv.cfg
 
then myproject folder will contain settings.py which we setup with all the details I put in the installation process

**Comment by foxmask** [comment]
done from http://trigger-happy.readthedocs.io/en/latest/quickstart.html#create-a-virtualenv
