### ISSUE TITLE
On trigger deletion, th_holidays should not be called if not used

### ISSUE THREAD

**Issue by nsteinmetz** [foxmask/django-th#127]
I didn't have th_hilidays enabled ; when deleting a trigger, it tries to remove stg from th_holidays which does not exist.

```
ProgrammingError at /th/trigger/delete/1

relation "django_th_holidays" does not exist
LINE 1: DELETE FROM "django_th_holidays" WHERE "django_th_holidays"....
```

**Comment by foxmask** [comment]
Did you try to install it before today ?
It looks like a delete  (cascade) from model TriggerService which is propagated to all the th_* appli

**Comment by foxmask** [comment]
aussi bizarre que cela puisse paraitre, pour shooter ce problème, il suffit de retirer une référence à holidays dans 2 endroits :   

* https://github.com/foxmask/django-th/blob/master/django_th/templates/mark_all.html#L7
* https://github.com/foxmask/django-th/blob/master/django_th/urls.py#L152

je verrai pour rajouter un test (si possible) dans le template et urls.py, du genre : 

    if 'th_holidays' in settings.INSTALLED_APPS:
