### ISSUE TITLE
Restyaboard integration

### ISSUE THREAD

**Issue by reidharry** [foxmask/django-th#137]
I'm looking to integrate Trigger Happy with [Restyaboard](https://github.com/RestyaPlatform/board)

Can I get the integration document, if any?

**Comment by foxmask** [comment]
First you need to have a Python lib that can use the API on this service

**Comment by foxmask** [comment]
If you have one then use the ansible module i made to create a trigger Happy easyly. https://trigger-happy.readthedocs.org/en/latest/new_module.html

**Comment by foxmask** [comment]
Then add the settings.py : 

```python
TH_SERVICES = (
'th_restyboard.my_restyboard.ServiceRestyboard',

TH_RESTYBOARD = (
    consumer_key: yourkey
    consumer_secret: tous effet
)
```

**Comment by foxmask** [comment]
Then you neeed to create the model to the database 

```shell
python manage.py makemigration
python manage.py migrate
```

**Comment by foxmask** [comment]
Nos you need to go to the admin panel to activate this new service like here https://trigger-happy.readthedocs.org/en/latest/quickstart.html#adding-the-service-pocket-from-the-admin

**Comment by foxmask** [comment]
Then go to the page of your activated service https://trigger-happy.readthedocs.org/en/latest/quickstart.html#activating-the-service click on new service button

**Comment by foxmask** [comment]
If you need more specifics details let me know

**Comment by reidharry** [comment]
Thanks a lot for your detailed explanation. Sure, i will ask if need any more details.

**Comment by foxmask** [comment]
That will be a pleasure to see a second person to have fun with the project.

**Comment by foxmask** [comment]
No api provided by this project 
Cant be done
