### ISSUE TITLE
RSS Digest

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#151]
Add the possibility to make digest (weekly/monthly) of Feed.

**Comment by karllhughes** [comment]
Yes. I'd get behind this. I've had an itch to build a service for myself to do it because I don't love IFTTT's.

**Comment by foxmask** [comment]
Here, it is a Big challenge to be able to keep a lot of data :)

**Comment by foxmask** [comment]
ee6984db7abf32538a68bec46df453afe968eb47
