### ISSUE TITLE
Trigger Happy and Taiga.io Kan ban ?

### ISSUE THREAD

**Issue by JtLively** [foxmask/django-th#155]
Is this feature possible as Taiga becomes more popular as an alternative to Trello ?

**Comment by foxmask** [comment]
If an api exists yes.

**Comment by JtLively** [comment]
Are you talking about all of this ?
https://taigaio.github.io/taiga-doc/dist/api.html

Or this ?
https://taigaio.github.io/taiga-doc/dist/

**Comment by foxmask** [comment]
I speak about API in general :) the one they provide is https://taigaio.github.io/taiga-doc/dist/api.html

**Comment by foxmask** [comment]
@JtLively 

Actually TriggerHappy can create github issue from a given Trello card or can create a Trello card from a github issue. 

Do you need the same scenario for Taiga ? If yes, I cant :/

If I'm not wrong, Currenlty the API does not permit to use KANBAN and so the card. If I miss it, can you point me to the page that use it ? 

Otherwise if we forget the kanban for now until it will be available, what do you need the most ?

**Comment by JtLively** [comment]
@foxmask The most important feature would be to notify a specified Slack channel of updates from a Taiga kan ban using some type of Webhook.

**Comment by foxmask** [comment]
So you also need slack ;)
For taigo kan ban i will have a look if webhook Can be used to request data from kan ban

**Comment by foxmask** [comment]
I asked to  the Taigo support some clarifications and I now can start :)

**Comment by bameda** [comment]
Taiga Team here ;-) maybe this can help you https://github.com/nephila/python-taiga.

**Comment by foxmask** [comment]
@bameda thank you ;)

**Comment by foxmask** [comment]
About webhook simple and powerful https://tree.taiga.io/support/integrations/webhooks/

**Comment by foxmask** [comment]
@JtLively part 1 : data on slack posted. Data come from my own blog feed

![data_posted_on_sack](https://cloud.githubusercontent.com/assets/208212/20458790/ced9c132-aeae-11e6-9528-2371948b64b1.png)

part 2 : to come, using Taigo.

The things that take much more time than another is to read to API :) 
Coding go fast. It's funny how all of this works :)

**Comment by foxmask** [comment]
@JtLively  do you know that a plugin already exists for publishing stuff from TAIGA to SLACK ?
![sans titre](https://cloud.githubusercontent.com/assets/208212/20546459/7a0e4498-b115-11e6-98fb-2ec20739da77.png)

**Comment by foxmask** [comment]
Sorry @bameda for all the time I disturbed you with something that alrady existed :/ Even If I keep all the things I did.

**Comment by foxmask** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/208212/20547020/9b5827f0-b119-11e6-888f-596d61254a55.png)
now Slack and Taiga speak altogether :)

**Comment by JtLively** [comment]
Yes, I use that. i thought django had a "if this, than that" function to add to that. Did I misunderstand something?

**Comment by foxmask** [comment]
I misunderstood. I thought you need it . I forgot that was a feature request. ;)

**Comment by JtLively** [comment]
I was asking about the ability to string together actions alongside that. If "keyword", then [action].

**Comment by foxmask** [comment]
This is not related to this issue, is it ?
If you mean several actions triggered for one given event, like [zapier](https://zapier.com/) does with gmail then dropbox then Slack, the answer is no. Not yet. 
But this goes beyond the scope of this small ticket ;) If I did not understood once again, can you explain/give an example ?

**Comment by JtLively** [comment]
This is what I was suggesting in the beginning. 
A Taiga notification goes to Slack with a specific word, phrase, or function (create, close,etc.)
Something else happens within Taiga or Slack.

**Comment by foxmask** [comment]
When one of those event will occurs 

-  a sprint is created, updated or deleted.
-  a user story is created, updated or deleted.
-  a task is created, updated or deleted.
-  an issue is created, updated or deleted.
-  a wiki page is created, updated or deleted.

Then TriggerHappy will receive that notification and will spread the data of [Taiga as explained here](https://tree.taiga.io/support/integrations/webhooks/).

The job that remain to be done is to distinguish each of those type of data to know how to customise the message to display on Slack (or anywhere else)

**Comment by bameda** [comment]
And epics!!!

**Comment by foxmask** [comment]
@bameda the doc does not speak about epics. Is it outdated ? ;)

**Comment by bameda** [comment]
yes.

**Comment by bameda** [comment]
It works like the rest of the objects.

**Comment by foxmask** [comment]
I could create a user story from slack to taiga :)
Slack&Taiga modules are now ok
