### ISSUE TITLE
Snapcraft

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#158]
Packaging for http://snapcraft.io/

If you successfully did such a packaging for a Python application or better for Django. 
If you could show me how, I take !

**Comment by foxmask** [comment]
Cant be done successfully

**Comment by raonyguimaraes** [comment]
Why not?

**Comment by foxmask** [comment]
Hi,
Because I spent a lot of months with help of one of the core dev of snapcraft and ubuntu contributor (he could make the project working but things were missing, and I didn't know how to fix them). 
And it's a lot of energy for something that won't be used. 
With almost 1000 stars, none of the stargazers use the project.
As I'm the first user of the project, all the existing modules are here because I use(d) them so I can maintain them, but I didn't for snapcraft I will never use.
So I think, at least, docker should be simplier.
If anyone wants to contribute to this topic, why not, but that would surprise me
Regards
