### ISSUE TITLE
Offer a Docker image for running Trigger Happy

### ISSUE THREAD

**Issue by meonkeys** [foxmask/django-th#162]
This is a feature request to create a Docker image for Trigger Happy. This would make it easy to try out TH and deploy it for reals.

https://hub.docker.com/_/python/ has suitable base and `-onbuild` images. Looks like one can create a `requirements.txt` file and an `-onbuild` image will run `pip install` on that.

**Comment by foxmask** [comment]
Hi,
Yes, I planed to try [cookiecutter-django as explained in that article](https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-via-docker/) to make Docker Image.

The idea is in my head since a year :) since the first user who installed the project.

**Comment by foxmask** [comment]
c0d2cf3c9c8bf47b87e442527447606760508edc 
4b3bb4a3725ae2168ef36bbc6410cc11753fe3ef

**Comment by meonkeys** [comment]
Nice! I reviewed the code and left a couple comments (right on the commits in GitHub).

I followed instructions in `README_docker.md`. I had to `sudo pip install docker-compose` first, and at the and I added `docker-compose -f docker-compose.yml run web  python manage.py runserver`.

I see:

```
$ docker-compose -f docker-compose.yml run web  python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
December 18, 2016 - 06:56:02
Django version 1.8.17, using settings 'django_th.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

But I can't hit any web server at that URL. Does it work for you?

**Comment by foxmask** [comment]
Hi,
I will check all if this but
Usually i dont push things that dont work.🤗
May be i forgot to  add command Line to the readme.
I'll tell you.

**Comment by foxmask** [comment]
i'm fedup with docker.
Each time I run docker, the result is NEVER the same .
I dropped docker and reinstall it and now the result is worst than ever.
```
container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 0 caused \"error running hook: exit status 1, stdout: , stderr: time=\\\"2016-12-18T18:31:17+01:00\\\" level=fatal msg=\\\"dial unix /run/docker/libnetwork/2de8bf691e08078172e11c76f66de9429d9daf6259666ad955f59a3ddc3c06ec.sock: connect: connection refused\\\" \\n\""
ERROR: Service 'web' failed to build: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2016-12-18T18:31:17+01:00\\\\\\\" level=fatal msg=\\\\\\\"dial unix /run/docker/libnetwork/2de8bf691e08078172e11c76f66de9429d9daf6259666ad955f59a3ddc3c06ec.sock: connect: connection refused\\\\\\\" \\\\n\\\"\"\n"
```
I dont understand what's going wrong.

**Comment by foxmask** [comment]
i tested again. If i use cookiecutter I cant use manage.py as I said here https://github.com/pydanny/cookiecutter-django/issues/895
If I use the guide https://docs.docker.com/compose/django/ I can't run migrate. I have to run makemigration but I dont agree with the changes made by it that modify the migrations scripts of the project.
So I give up, until a new try or help by somebody else who know how to do all of that.

**Comment by foxmask** [comment]
I finished by doing this https://github.com/foxmask/django-th/blob/master/README_docker.md

Which seems to work as I can reach the url http://0.0.0.0:8000/th/

**Comment by meonkeys** [comment]
Nice! I'm able to hit http://localhost:8000/th/ and log in as root.

:+1:

**Comment by foxmask** [comment]
Do not hesitate to ask if you need help

**Comment by meonkeys** [comment]
Will do, thanks! I'm just poking around TH now. Looks cool.
