### ISSUE TITLE
Probleme de routing

### ISSUE THREAD

**Issue by JulesMichael** [foxmask/django-th#181]
Salut,

Je viens d'installer Django-th mais apparemment il doit y avoir un problème au niveau du routing des fichiers statics. Les urls mènent à une 404.

![capture d ecran 2017-06-15 a 09 26 21](https://user-images.githubusercontent.com/11298738/27170030-b88ecf48-51ac-11e7-9718-f0ec140b98c9.png)

![capture d ecran 2017-06-15 a 09 20 41](https://user-images.githubusercontent.com/11298738/27169893-2f6f9e0e-51ac-11e7-9690-acae3a107312.png)

**Comment by foxmask** [comment]
dans le fichier de settings  : 
* si c'est pour sa workstation pour tester, on met 

```python
DEBUG =True 
ALLOWED_HOSTS = ['*']
```

si c'est pour un serveur en prod on met 

```python
 DEBUG = False 
ALLOWED_HOSTS = ['localhost', '127.0.0.1'] 
```
la valeur de allowed_hosts sera à ajuster avec le nom de son serveur par exemple

**Comment by JulesMichael** [comment]
Merci nickel !
