### ISSUE TITLE
Collect Stats

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#186]
When a trigger finishes successfully, or fails: 

1. store the number of time a trigger has been done (successfully or not)
1.2. by trigger
1.3. by service

**Comment by foxmask** [comment]
changes needed to add the counter of those models:
* model TriggerService 
* model UserService 
and modify [this](https://github.com/foxmask/django-th/blob/master/django_th/models/__init__.py#L151-L175) to handle that counter

**Comment by H-Chauhan** [comment]
Please assign this to me

**Comment by foxmask** [comment]
ok it's for you :+1:

**Comment by H-Chauhan** [comment]
Thanks. I'm new here, can you please elaborate a little more, what has to be done?

**Comment by foxmask** [comment]
I hope you know Django otherwise you'll be lost.

for that issue, I would like to add 2 columns counter_ok, counter_ko for models TriggerService and UserService, 
And in that [function](https://github.com/foxmask/django-th/blob/master/django_th/models/__init__.py#L151-L175) (that store the result of each TriggerService) update the counters in that 2 models

The structure of the project is : 

- UserService store for a user, his service
- TriggerService store for a user, the trigger we've setup for 2 services (one consumer one provider)

those 2 are linked like [this](https://github.com/foxmask/django-th/blob/master/django_th/models/__init__.py#L96-L97)

So to be able to count each time the service of a user worked, I need to update UserService and TriggerService

In https://github.com/foxmask/django-th/blob/master/django_th/models/__init__.py#L151-L175 we know everything on TirggerService

So something like 
```
    if status:
        service = TriggerService.objects.get(id=trigger_id)
        TriggerService.objects.filter(id=trigger_id).update(result=msg,
                                                            date_result=now(),
                                                            provider_failed=0,
                                                            consumer_failed=0,
                                                           counter_ok=ts.counter_ok + 1)
         UserService.objects.filter(user=service.user,name=service.consumer.name.name).update(
counter_ok=service.counter_ok + 1)
    else:
        service = TriggerService.objects.get(id=trigger_id)

         UserService.objects.filter(user=service.user,name=service.consumer.name.name).update(
counter_ko=service.counter_ko + 1)

        failed = service.consumer_failed + 1
        if failed > settings.DJANGO_TH.get('failed_tries', 5):
            TriggerService.objects.filter(id=trigger_id).\
                update(result=msg, date_result=now(), status=False, counter_ko=ts.counter_ko + 1)
        else:
            TriggerService.objects.filter(id=trigger_id).\
                update(result=msg, date_result=now(), consumer_failed=failed,counter_ko=ts.counter_ko + 1)

        warn_user_and_admin('consumer', service)
```

then we could used it page on the service and in page of the triggers (i could give you details about where there are if you feel ok to continue).

**Comment by H-Chauhan** [comment]
Yeah, I am comfortable with Django. Thanks.

**Comment by foxmask** [comment]
ok, so
1)  in the template of the triggers list  (templates/home.html) we could use something like this 
```
<span class="badge">{{ trigger.counter_ok }}</span> {%  trans "ran successfully" %} - <span class="badge">{{ trigger.counter_ko }}</span> {%  trans "failed" %}
```
in that [node](https://github.com/foxmask/django-th/blob/master/django_th/templates/home.html#L71-L73)

we need to add the same piece of html in that part of that [template](https://github.com/foxmask/django-th/blob/master/django_th/templates/triggers/trigger_line.html#L26-L28), because this template is used for an Ajax response (when we activate/deactive a trigger)

2)  and in the template of the services (templates/services/services.html) 
```
<span class="badge">{{ service.counter_ok }}</span> {%  trans "ran successfully" %} - <span class="badge">{{ service.counter_ko }}</span> {%  trans "failed" %}
```
[may be here](https://github.com/foxmask/django-th/blob/master/django_th/templates/services/services.html#L51)

If you have any question, let me know

**Comment by H-Chauhan** [comment]
There are problems with migrations with model th_wallbag. There are already pending changes in the models that needed to be migrated.

**Comment by foxmask** [comment]
This is due to the fact that I separate the migrations of each `th_<service>` in its own folder, but as I used the same "app_label" (in models.py), it seems that django, group all the migrations in the folder django_th/migrations/.
Finally if you look at the content of the migration that was generated it should do : 
drop table in th_wallabag/migrations
create table in django_th/migrations
If it's the case, It's not important, go on:) otherwise if you can show me what are the pending changes

**Comment by H-Chauhan** [comment]
Actually, Django runs migrations in by alphabetical order of apps, regardless of their created time, unless there is a dependency. So I created the dependency in the migration. Also I have done the editions in the template.

However, the unit tests of form validations of UserService and TriggerService are failing.

I am creating a PR.

**Comment by foxmask** [comment]
yes they should failed, it's logic, those new columns are not tested yet. I will have a look at them .
