### ISSUE TITLE
remove admin to urls.py

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#187]
run the commands 

```python
python manage.py check --deploy

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
```
then to fix that, in urls.py replace that :

```python
             # ****************************************
             # admin module
             # ****************************************
             url(r'^admin/', include(admin.site.urls)),
```

by that : 

```python
             # ****************************************
             # admin module
             # ****************************************
             # url(r'^admin/', include(admin.site.urls)),
```

**Comment by RishabhJain2018** [comment]
@foxmask Can I take this up?

**Comment by foxmask** [comment]
if you want to participate to the [hacktoberfest](https://hacktoberfest.digitalocean.com/), register and wait for october 1rst, then you could take it :)

**Comment by RishabhJain2018** [comment]
@foxmask No doubt, I will participate in hacktoberfest but as I was going through your repository and I found easy to fix the issue while getting the idea of the codebase. For the hacktoberfest , I will solve other issues too. The idea is of contribution & participation is secondary :)

**Comment by foxmask** [comment]
i've just opened this issue for hacktoberfest :)
cant you wait for sunday ?

**Comment by RishabhJain2018** [comment]
Yes sure :)

**Comment by Owanesh** [comment]
Sorry @RishabhJain2018 and @foxmask   for the commit, I did not want to steal the fix, I just did not see the assignment of the issue.

Good game at all 😇

**Comment by foxmask** [comment]
@RishabhJain2018 are you still on that issue ?

**Comment by RishabhJain2018** [comment]
@foxmask is it still open? I think @Owanesh has solved it.

**Comment by foxmask** [comment]
no because I told him you worked on it.

**Comment by RishabhJain2018** [comment]
ohh..okay. I will fix this in few hours. :)
