### ISSUE TITLE
from the settings.py, drop all 'th_<service>'  cache

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#190]
from [here](https://github.com/foxmask/django-th/blob/master/django_th/settings.py#L216-L376) keep [this piece](https://github.com/foxmask/django-th/blob/master/django_th/settings.py#L356-L376) and [this piece](https://github.com/foxmask/django-th/blob/master/django_th/settings.py#L216-L225). 

Then from all `th_<service>/my_<service>.py` module (and `th_<service>/tests.py`), replace 

```
cache = caches['th_<service>'] 
```
by
```
cache = caches['django_th']
```
and for each UnitTest (in `th_<service>/tests.py`)
[drop this](https://github.com/foxmask/django-th/blob/master/th_rss/tests.py#L62-L63)

**Comment by CrazyLlama** [comment]
See #192 😃

**Comment by foxmask** [comment]
I presume that you dont want to participate to the hacktoberfest ?
because the rule is to make a PR between 1 and 31 of october

**Comment by CrazyLlama** [comment]
Oh no, I will be I'm just getting back in the swing of things with github. I can cancel this now and resubmit in the time period if you'd prefer?

**Comment by CrazyLlama** [comment]
Yeah I'll resubmit then, sorry!

**Comment by foxmask** [comment]
yes it will be better if you want to participate :)
