### ISSUE TITLE
updating doc 

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#191]
that will reflect changes on #188 #189 #190

**Comment by Logan1x** [comment]
I would like to work on this issue @foxmask

**Comment by foxmask** [comment]
if you want to participate to the [hacktoberfest](https://hacktoberfest.digitalocean.com/), register and wait for october 1rst before submitting the PR.

**Comment by Logan1x** [comment]
i Want to know what changes you want in pr?

**Comment by foxmask** [comment]
once issues #188 #189 #190 will be done, we need to change each doc from https://github.com/foxmask/django-th/blob/master/docs/

for example for Evernote
https://github.com/foxmask/django-th/blob/master/docs/evernote.rst

drop the cache part, as it will desapear

then, the section "the service keys"
```
The service keys
It's strongly recommended that your put the following in a local_settings.py, to avoid to accidentally push this to a public repository
TH_EVERNOTE = {
    'sandbox': True,  # set it to False when in production
    'consumer_key': 'my key',
    'consumer_secret': 'my secret',
}
```
will become 
```
The service keys:

in the .env file set the following parameters 
TH_EVERNOTE_SANDBOX = False 
TH_EVERNOTE_CONSUMER_KEY = 'your consumer key'
TH_EVERNOTE_CONSUMER_SECRET' =  'your consumer secret'
```

we dont need to speak about local_settings.py at all nor about the TH_EVERNOTE parms too because in the issue #188 it will become generic like this
```
TH_EVERNOTE = {
    'sandbox': env('TH_EVERNOTE_SANDBOX')
    'consumer_key': env('TH_EVERNOTE_CONSUMER_KEY')
    'consumer_secret':  env('TH_EVERNOTE_CONSUMER_SECRET')
}
```

**Comment by foxmask** [comment]
all issues are fixed - the doc can be update if you still want to deal with this ticket

**Comment by Logan1x** [comment]
what doc's need to be updated?

**Comment by foxmask** [comment]
Hi,
For each service:

* Drop the chapter "Cache", as the dedicated cache for each service has been removed from the code
* Change the chapter "service keys"  as explains [above](https://github.com/foxmask/django-th/issues/191#issuecomment-332798233). In the [env.sample](https://github.com/foxmask/django-th/blob/master/django_th/env.sample) file, you will find all the services with the variables to put in each doc.

Thank you.

**Comment by Logan1x** [comment]
we need to change this to 

![selection_011](https://user-images.githubusercontent.com/10944610/31376600-2029b45c-adc3-11e7-942f-610ea3582dfc.png)

this ...right?
![selection_012](https://user-images.githubusercontent.com/10944610/31376603-22597a32-adc3-11e7-86ee-00b5c6004fea.png)

**Comment by foxmask** [comment]
yes !

We also need to tell where we set this values (in the `.env` file)

**Comment by Logan1x** [comment]
didn't understand this part 

> We also need to tell where we set this values (in the .env file)

**Comment by Logan1x** [comment]
and what should i fill in those value consumer , consumer secret , sandbox?

**Comment by Logan1x** [comment]
why did you can the value of sandbox to true  `      'sandbox': True,  # set it to False when in production` to ` TH_EVERNOTE_SANDBOX = False `

is this because we are in production stage?

**Comment by foxmask** [comment]
Yes

**Comment by Logan1x** [comment]
Ok I understood now  I'll work on it😊

**Comment by Logan1x** [comment]
> TH_EVERNOTE_CONSUMER_SECRET'=  'your......

what does this (') quote before "="  stand's for in the line

when using this 'your consumer secret' is not highlighting...

![selection_014](https://user-images.githubusercontent.com/10944610/31424941-9dca4108-ae7a-11e7-8300-bbfea998d14b.png)

**Comment by foxmask** [comment]
typo

**Comment by Logan1x** [comment]
ok you did both the time ( [here](https://github.com/foxmask/django-th/issues/191#issuecomment-332798233) and [here again](https://github.com/foxmask/django-th/issues/191#issuecomment-335405879) ) that's why i thought it's not a typo

**Comment by foxmask** [comment]
no it's a typo :) i didnt check the full render of the example I gave.

**Comment by Logan1x** [comment]
but if i add then 'your consumer secret' will not highlight.

**Comment by foxmask** [comment]
if you can come on [gitter.im](https://gitter.im/foxmask/django-th) then you could speak about that and exchange on that problem through http://dpaste.com/ :)
