### ISSUE TITLE
admin page of triggers - simplifing the filter list

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#198]
On the page http://localhost:8000/admin/django_th/triggerservice/, the content list of the filter, at the right of the page, should to be reduced.

Actually :
For each Trigger, there is systematically ServiceA ServiceB in the list of the filter.
Same behavior with user (there are as far as user than trigger) 

Expected Result:
- The list of servirces should be reduced to the data of the ServicesActivated (model) which will list the services only once and this will avoid to inflate  the page
- For 'user' we just need to display the auth_user model (i suppose) to filter to current Triggerservice list for a given user

**Comment by H-Chauhan** [comment]
I'm on it.

**Comment by H-Chauhan** [comment]
I have created the PR #203. I have simplified services filter list to contain the ServicesActivated only.

Since the User is already FK to auth_user_model, so by default it shows entries from auth_user_model. Do you want the filter list to contain the related users only instead of all?

**Comment by foxmask** [comment]
Yes that's be fine
