### ISSUE TITLE
admin page of user services - simplifying the filter list

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#199]
On the page http://localhost:8000/admin/django_th/userservice/, the content list of the filter, at the right of the page, should to be reduced.

Actually :
For each UserService, there are as far as user than userservice entries

Expected Result:
-   For 'user' we just need to display the auth_user model (i suppose) to filter to current userservice list for a given user

**Comment by vaibhavsingh97** [comment]
@foxmask Can i work on this?

**Comment by foxmask** [comment]
yes sure.
if you want to participate to the [hacktoberfest](https://hacktoberfest.digitalocean.com/), dont forget to register :)

**Comment by vaibhavsingh97** [comment]
@foxmask I tried to install locally, but i am not abe to run :(

**Comment by foxmask** [comment]
what's the problem ?

**Comment by foxmask** [comment]
you need to do : 

1) clone the repo for you
2) python3.6 -m venv foxmask (for example)
3) git clone your repo
4) cd to the django-th
5) source ../bin/activate
6) pip install -r requirements.txt 
7) ./manage.py migrate
8) ./manage.py runserver

**Comment by foxmask** [comment]
http://localhost:8000/th/ is the main page of the project 
http://localhost:8000/admin/ for the admin page

**Comment by vaibhavsingh97** [comment]
@foxmask Small issue before i fix this 😄 
![image](https://user-images.githubusercontent.com/8705386/31095142-49030d78-a7a7-11e7-9dcd-a60d169da4f1.png)

**Comment by foxmask** [comment]
set DEBUG to True :)

**Comment by vaibhavsingh97** [comment]
@foxmask This behaviour i have seen for first time, when `debug=true` everything working smoothely but `debug=false` everything breaks

**Comment by foxmask** [comment]
Yes I know. I thought I fixed it earlier. I'm going to check if a CSS is not missing.

**Comment by foxmask** [comment]
it's ok when debug is set to False and the HTTP config point on the static folder correctly

if the result of collectstatic is in `/home/foxmask/DjangoVirtualEnv/django-trigger-happy36/django-th/static`, then, for example for nginx i'll do
```ini
    # ROOT website
    root  /home/foxmask/DjangoVirtualEnv/django-trigger-happy36/django-th/;
    location /static/ {
            root  /home/foxmask/DjangoVirtualEnv/django-trigger-happy36/django-th/;
    }
```
does the trick

**Comment by foxmask** [comment]
I think, I will set DEBUG to False and add to the doc how to manage when set DEBUG to True and set NGINX  config

**Comment by vaibhavsingh97** [comment]
@foxmask 👍   I was going throught the codebase and also can you please exlain what i have to do as i am not able to understand 😅

**Comment by foxmask** [comment]
Actually, that page http://localhost:8000/admin/django_th/userservice/ display the list of the service that one user has decided to enable for his own usage.
If there are 5 users that have enabled 10 services I have a list of 50 users in the filter list.
I would like to reduced this list in the filter list (at the right of the page), by only displaying one user and when I select one user, this should filter and only display the service of that user.

nota : as the users are in the auth_user model, I dont know if such a thing is possible to do in the admin on the UserService page ?

**Comment by h-chauhan** [comment]
Is anyone still working on this? Can I grab this one?

**Comment by foxmask** [comment]
Hi I think that if vaibhavsingh97 does not reply  tomorrow, then you have my agreement to work on it

**Comment by vaibhavsingh97** [comment]
@foxmask I am trying my best to fix this issue, Gimme some time 😄

**Comment by foxmask** [comment]
No pb :)

**Comment by foxmask** [comment]
@vaibhavsingh97 can I accept the @scomert PR or you are still on that issue ?

**Comment by vaibhavsingh97** [comment]
@foxmask Yes, Please...i had exams so i was not able to work.

**Comment by foxmask** [comment]
thank you
and good luck for exams
