### ISSUE TITLE
 insert default data after migrations

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#200]
from this tables, 
![services](https://user-images.githubusercontent.com/208212/31099490-75bd39e6-a7c6-11e7-954f-704642038b8b.png)

generate a fixture file that could be imported after 

```
python manage.py migrate
```

by
 
```
python manage.py loaddata initial_services.json
```
for example

But at first, just RSS and Wallabag will be activated

Once it's done, adding to the doc, the command to enter to load them. [in the parragraph "database"](https://github.com/foxmask/django-th/blob/master/docs/quickstart.rst)

**Comment by denvaar** [comment]
I'm on it 👍
