### ISSUE TITLE
docker file

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#217]
Update the docker file to set enable all services instead of just th_RSS and th_wallabag 
As we now use django- environ  this should be simplier

**Comment by knil-sama** [comment]
Hi @foxmask, can I take this ?

**Comment by foxmask** [comment]
if you want to participate to the [hacktoberfest](https://hacktoberfest.digitalocean.com/), register and wait for october 1rst, then you could take it :)

**Comment by foxmask** [comment]
added fixture to installation process e8b1fb6

**Comment by knil-sama** [comment]
@foxmask Sorry I didn't found time to finish

**Comment by foxmask** [comment]
no problem :)
