### ISSUE TITLE
Thanks you all

### ISSUE THREAD

**Issue by foxmask** [foxmask/django-th#258]
Hi, 

@Koalie, @CrazyLlama, @Logan1x, @h-chauhan, @RishabhJain2018, @denvaar, @alonisser, @Pal0r, @scomert, @pohzipohzi

In case you didnt see the [blog post](https://blog.trigger-happy.eu/django-trigger-happy-1.5.0-hacktoberfest.html), I  deeply address a warm thanks for all your work during this [Hacktoberfest](https://hacktoberfest.digitalocean.com/).
I could released this 1.5.0 named "[Hacktoberfest](https://github.com/foxmask/django-th/milestone/22)" version because of you !

**Comment by koalie** [comment]
I did see the blog post. It was a pleasure!
My thanks for you for that project in the first place!
