### ISSUE TITLE
Limit max item pushed at during a session to avoid a flood effect

### ISSUE THREAD

**Issue by nsteinmetz** [foxmask/django-th#88]
To avoid flood effect when you do something wrong with TH, it would be nice if we could set a limit of items being pushed when fire_th is executed.

Ex : I just pushed 31 items to twitter as I made a typo in my crontab. So when I fixed it, it took all the items which were not fetched so far.

I would be nice for ex if I had set up a threshold to 5 items that this 31 items would have been published  over the next 7 times where fire_th is run. (5+5+5+5+5+5+1). Of course, if new items are added in the queue in the meanwhile, it's added in the queue list.

**Comment by foxmask** [comment]
do you meet an error ?

**Comment by nsteinmetz** [comment]
Nope no error - just a queue/flood management solution to avoid having my twitter timeline angry with me once I fix my script !

Yes it's almost the same topic as the one you describe on indexerror.net.

**Comment by foxmask** [comment]
if they are hungry i suppose they dont follow the president of APRIL ;) 'cause he does flood too :D (and no he does not use TH). 
But as you can see I'm consciens of the problem
It just takes a lot of time for me to digg the best solution.

**Comment by nsteinmetz** [comment]
If they're hungry, they just have to eat ;-)

More seriously, if I can help somehow, let me know. I don't have a lot of bandwith right now for new topics but I'd be happy to contribute to some extend. At least, I can discuss the point with you.

**Comment by foxmask** [comment]
it's tea time ; i'm hungry :D 
currently the project need #51 and cache system that consist to grab data put them in a queue and only handle the queue if not empty etc

**Comment by foxmask** [comment]
Celery handles that behavior 
http://docs.celeryq.org/en/latest/userguide/workers.html#rate-limits
http://docs.celeryq.org/en/latest/reference/celery.app.control.html#celery.app.control.Control.rate_limit

**Comment by foxmask** [comment]
working on it

**Comment by foxmask** [comment]
5b29b8a7ae1193425ea8bd77a3389c4c2083bc09

**Comment by nsteinmetz** [comment]
Hello !

Top ! Donc testable après un simple git pull ? Ou il y a des choses en plus à faire ? Vu la tête du commit, hormis définir le seuil, je ne vois pas grand chose à faire. Il faut celery & co par contre ?

Merci :)

**Comment by foxmask** [comment]
non un simple git pull le fait pas, parce qu'à présent : 

1) il ya eu une modif sur le model de th_rss (ajout d'une colonne uuid pour generer des flux rss)
2) j'ai mis tous les modules dans le dossier django_th

patiente un peu que je teste depuis une version antérieure vers 'master'

**Comment by nsteinmetz** [comment]
Ok, ça marche, j'attends ton feu vert et tes instructions ;-)
